version: '3.8'

services:
  mongo1:
    container_name: mongo1
    image: mongo:4.4
    volumes:
      - ./scripts/rs-init.sh:/scripts/rs-init.sh
      - ./scripts/init.js:/scripts/init.js
    networks:
      - mongo-network
    ports:
      - 27017:27017
    depends_on:
      - mongo2
      - mongo3
    links:
      - mongo2
      - mongo3
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "dbrs" ]

  mongo2:
    container_name: mongo2
    image: mongo:4.4
    networks:
      - mongo-network
    ports:
      - 27018:27017
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "dbrs" ]
  mongo3:
    container_name: mongo3
    image: mongo:4.4
    networks:
      - mongo-network
    ports:
      - 27019:27017
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "dbrs" ]
  percona:
    image: percona/percona-backup-mongodb:latest
    container_name: percona
    environment:
      PBM_MONGODB_URI: "mongodb://pbmuser:secretpwd@mongo1:27017/?authSource=admin&replSetName=dbrs"
    user: root
    networks:
    - mongo-network
    volumes:
      - ./pbm_config.yaml:/tmp/pbm_config.yaml
      - ./shared-volume:/backup/
     # - ./shared-volume:/backup/pbmPitr/dbrs

    depends_on:
      - mongo1

  percona-mongo2:
    image: percona/percona-backup-mongodb:latest
    container_name: percona-mongo2
    user: root
    environment:
      PBM_MONGODB_URI: "mongodb://pbmuser:secretpwd@mongo2:27017/?authSource=admin&replSetName=dbrs"
    networks:
    - mongo-network
    volumes:
      - ./pbm_config.yaml:/tmp/pbm_config.yaml
      - ./shared-volume:/backup/
     # - ./shared-volume:/backup/pbmPitr/dbrs

    depends_on:
      - mongo2
  percona-mongo3:
    image: percona/percona-backup-mongodb:latest
    container_name: percona-mongo3
    user: root
    environment:
      PBM_MONGODB_URI: "mongodb://pbmuser:secretpwd@mongo3:27017/?authSource=admin&replSetName=dbrs"
    networks:
    - mongo-network
    volumes:
      - ./pbm_config.yaml:/tmp/pbm_config.yaml
      - ./shared-volume:/backup/
     # - ./shared-volume:/backup/pbmPitr/dbrs

    depends_on:
      - mongo3
volumes:
  shared-volume:
  
networks:
  mongo-network:
    driver: bridge